In [1]:
import numpy as np
import pandas as pd

In [75]:
### loading Books.csv file
books = pd.read_csv("Books.csv", on_bad_lines="skip")

C:\Users\unive\AppData\Local\Temp\ipykernel_24692\3772335880.py:2: DtypeWarning: Columns (0: Year-Of-Publication) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv", on_bad_lines="skip")

In [76]:
books.head(1)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...

In [77]:
books = books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher']]

In [78]:
books.head(1)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press

In [79]:
books.rename(columns={
    'Book-Title' : 'title',
    'Book-Author' : 'author',
    'Year-Of-Publication' : 'year',
    'Publisher' : 'publisher'
}, inplace=True)

In [80]:
books.columns

Index(['ISBN', 'title', 'author', 'year', 'publisher'], dtype='str')

In [81]:
### loading Users.csv file
users = pd.read_csv("Users.csv", on_bad_lines="skip")

In [82]:
users.head(2)

   User-ID                   Location   Age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [83]:
users.rename(columns={
    'User-ID' : 'user_id',
    'Location' : 'location',
    'Age' : 'age'
}, inplace=True)

In [84]:
users.head(2)

   user_id                   location   age
0        1         nyc, new york, usa   NaN
1        2  stockton, california, usa  18.0

In [85]:
ratings = pd.read_csv("Ratings.csv", on_bad_lines="skip")

In [86]:
ratings.head(1)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0

In [87]:
ratings.rename(columns={
    "User-ID" : "user_id",
    "Book-Rating" : "rating"
}, inplace=True)

In [88]:
ratings.head(1)

   user_id        ISBN  rating
0   276725  034545104X       0

In [89]:
books.shape

(271360, 5)

In [90]:
users.shape

(278858, 3)

In [91]:
ratings.shape

(1149780, 3)

In [92]:
ratings["user_id"].value_counts()

user_id
11676     13602
198711     7550
153662     6109
98391      5891
35859      5850
          ...
276697        1
276706        1
276709        1
276721        1
276723        1
Name: count, Length: 105283, dtype: int64

In [93]:
ratings["user_id"].value_counts().shape

(105283,)

In [94]:
x = ratings["user_id"].value_counts() > 200
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
276697    False
276706    False
276709    False
276721    False
276723    False
Name: count, Length: 105283, dtype: bool

In [95]:
x[x].shape

(899,)

In [96]:
y = x[x].index
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,   9856,  28634,  44296,  59727,  73681, 155916, 188951, 268622,
       274808],
      dtype='int64', name='user_id', length=899)

In [97]:
### extracting ratings of people who rated atleast 200 books
ratings = ratings[ratings["user_id"].isin(y)]

In [98]:
ratings.shape

(526356, 3)

In [99]:
### merge ratings and books
ratings_with_books = ratings.merge(books, on = "ISBN")

In [100]:
ratings_with_books.head()

,user_id,ISBN,rating,title,author,year,publisher
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons
2,277427,003008685X,8,Pioneers,James Fenimore Cooper,1974,Thomson Learning
3,277427,0030615321,0,"Ask for May, Settle for June (A Doonesbury book)",G. B. Trudeau,1982,Henry Holt &amp; Co
4,277427,0060002050,0,On a Wicked Dawn (Cynster Novels),Stephanie Laurens,2002,Avon Books

In [101]:
ratings_with_books.shape

(487671, 7)

In [106]:
### Group the rows by book title, then count how many ratings each book has received.
ratings_with_books.groupby('title')['rating'].count()

title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    2
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
 Clifford Visita El Hospital (Clifford El Gran Perro Colorado)                                                1
                                                                                                             ..
Ã?Â?ber die Pflicht zum Ungehorsam gegen den Staat.                                                           3
Ã?Â?lpiraten.                                                                                                 1
Ã?Â?rger mit Produkt X. Roman.                                                                                1
Ã?Â?stlich der Berge.                                                                                         1
Ã?Â?thique en toc                                                                                             1
Name: rating, Length: 160269, dtype: int64

In [112]:
number_rating = ratings_with_books.groupby('title')['rating'].count().reset_index()

In [115]:
number_rating.head(2)

                                               title  rating
0   A Light in the Storm: The Civil War Diary of ...       2
1                              Always Have Popsicles       1

In [116]:
number_rating.rename(columns={
    "rating" : "number of ratings"
}, inplace=True)

In [ ]:
number_rating.head(2)

                                               title  number of ratings
0   A Light in the Storm: The Civil War Diary of ...                  2

In [119]:
number_rating.shape

(160269, 2)

In [121]:
### merging ratings_with_books and number_rating
final_rating = ratings_with_books.merge(number_rating, on='title')

In [124]:
final_rating.head(2)

,user_id,ISBN,rating,title,author,year,publisher,number of ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,82
1,277427,0026217457,0,Vegetarian Times Complete Cookbook,Lucy Moll,1995,John Wiley &amp; Sons,7

In [125]:
final_rating['number of ratings'] >= 50

0          True
1         False
2         False
3         False
4         False
          ...
487666    False
487667    False
487668    False
487669    False
487670    False
Name: number of ratings, Length: 487671, dtype: bool

In [127]:
final_rating = final_rating[final_rating['number of ratings'] >= 50]

In [132]:
final_rating.shape

(61853, 8)

In [134]:
final_rating.drop_duplicates(['user_id', 'title'], inplace=True)

In [135]:
final_rating.shape

(59850, 8)

In [136]:
book_pivot = final_rating.pivot_table(columns='user_id', index='title', values='rating')

In [138]:
book_pivot.shape

(742, 888)

In [139]:
book_pivot

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84 Charing Cross Road,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,7.0,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [140]:
book_pivot.fillna(0, inplace=True)

user_id,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
84 Charing Cross Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,7.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [141]:
# Ratings
#    ↓
# final_rating
#    ↓
# pivot_table()
#    ↓
# Book × User matrix
#    ↓
# Similarity calculation
#    ↓
# Find similar books
#    ↓
# Recommendations

In [142]:
from scipy.sparse import csr_matrix
book_sparse = csr_matrix(book_pivot)

In [ ]:
# csr_matrix : it's useful because your book_pivot matrix will contain a huge number of zeros/missing values.
# CSR means :
# Compressed Sparse Row

# Instead of storing every 0, it mainly stores the non-zero values and their locations.

In [ ]:
print(book_sparse)
# book_sparse.shape

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 14961 stored elements and shape (742, 888)>
  Coords	Values
  (0, 0)	9.0
  (0, 16)	8.0
  (0, 37)	9.0
  (0, 42)	8.0
  (0, 59)	7.0
  (0, 135)	9.0
  (0, 156)	10.0
  (0, 170)	9.0
  (0, 187)	8.0
  (0, 220)	10.0
  (0, 221)	10.0
  (0, 277)	10.0
  (0, 359)	10.0
  (0, 370)	9.0
  (0, 389)	10.0
  (0, 477)	9.0
  (0, 491)	7.0
  (0, 507)	9.0
  (0, 554)	10.0
  (0, 604)	9.0
  (0, 611)	8.0
  (0, 695)	9.0
  (0, 734)	9.0
  (0, 762)	8.0
  (0, 769)	7.0
  :	:
  (740, 484)	8.0
  (740, 681)	9.0
  (741, 16)	8.0
  (741, 26)	7.0
  (741, 86)	10.0
  (741, 111)	5.0
  (741, 150)	6.0
  (741, 233)	7.0
  (741, 290)	8.0
  (741, 303)	9.0
  (741, 322)	10.0
  (741, 367)	10.0
  (741, 384)	9.0
  (741, 446)	7.0
  (741, 450)	9.0
  (741, 485)	7.0
  (741, 498)	10.0
  (741, 505)	8.0
  (741, 544)	10.0
  (741, 592)	8.0
  (741, 700)	10.0
  (741, 713)	8.0
  (741, 745)	10.0
  (741, 830)	9.0
  (741, 880)	8.0

In [144]:
type(book_sparse)

scipy.sparse._csr.csr_matrix

In [145]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [ ]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [161]:
book_pivot.iloc[237].values.reshape(1,-1).shape

(1, 888)

In [179]:
distances, suggestions = model.kneighbors(book_pivot.iloc[237].values.reshape(1,-1), n_neighbors=6)

In [180]:
distances

array([[ 0.        , 67.75691847, 68.05145112, 72.277244  , 75.81556568,
        76.30203143]])

In [ ]:
suggestions.shape # it is a 2D array

(1, 6)

In [181]:
suggestions

array([[237, 238, 240, 241, 184, 536]])

In [182]:
for i in range(len(suggestions)):
    print(book_pivot.index[suggestions[i]])

Index(['Harry Potter and the Chamber of Secrets (Book 2)',
       'Harry Potter and the Goblet of Fire (Book 4)',
       'Harry Potter and the Prisoner of Azkaban (Book 3)',
       'Harry Potter and the Sorcerer's Stone (Book 1)', 'Exclusive',
       'The Cradle Will Fall'],
      dtype='str', name='title')

In [185]:
book_pivot.index[237]

'Harry Potter and the Chamber of Secrets (Book 2)'

In [188]:
# book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)'
np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')

(array([237]),)

In [192]:
print(np.where(book_pivot.index == 'Harry Potter and the Chamber of Secrets (Book 2)')[0][0])

237

### Function to recommend books.

In [211]:
def recommend_book(book_name):
    book_id = np.where(book_pivot.index == book_name)[0][0]
    distances, suggestions = model.kneighbors(book_pivot.iloc[book_id].values.reshape(1,-1), n_neighbors=6)
    print(f"The suggestions for {book_name} are :")
    for i in range(len(suggestions[0])):  # here suggestions is a 2D array
        if i!=0:
            print(f"{i}. {book_pivot.index[suggestions[0][i]]}")

In [213]:
recommend_book('Animal Farm')

The suggestions for Animal Farm are :
1. Exclusive
2. Jacob Have I Loved
3. Second Nature
4. Pleading Guilty
5. No Safe Place

In [214]:
recommend_book('Harry Potter and the Chamber of Secrets (Book 2)')

The suggestions for Harry Potter and the Chamber of Secrets (Book 2) are :
1. Harry Potter and the Goblet of Fire (Book 4)
2. Harry Potter and the Prisoner of Azkaban (Book 3)
3. Harry Potter and the Sorcerer's Stone (Book 1)
4. Exclusive
5. The Cradle Will Fall